name: Deploy Strapi to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.19.1'

    - name: Install Strapi CLI
      run: |
        sudo npm install strapi@latest -g

    - name: Install Global Dependencies
      run: |
        sudo npm install yarn -g

    - name: Install Project Dependencies and Build
      run: |
        yarn install
        yarn build

    - name: Deploy to EC2
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no -i $EC2_KEY $EC2_USER@$EC2_HOST << 'EOF'
          cd /my-project
          git pull origin main
          npm install
          strapi build
          # Adjust the following command as per your deployment needs
          NODE_ENV=production npm run start
        EOF
